# Railway will auto-detect Python from backend folder
# Just set the root directory to 'backend' in Railway dashboard
# SMTP_SERVER, SMTP_PORT, SMTP_USERNAME, SMTP_PASSWORD - email config
# FRONTEND_URL - your Netlify frontend URL
